config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :destroy] do
    collection do
      get :assign_tag
      put :assign_tag_to
    end
  end

  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_tags
  has_many :tags, through: :book_tags

  validates :title, length: { maximum: 255 },  uniqueness: true, presence: true
  validates :description, presence: true
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
  validates :tag_id, :uniqueness => { :scope => :book_id }
  validates :tag_id, presence: true
  validates :book_id, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :book_tags
  has_many :books, through: :book_tags

  validates :name, length: { maximum: 255 }, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @tags = Tag.all
    handle_search
    respond_to do |format|
      format.html { @books }
      format.json { render json: { books: @books } }
    end
  end

    def destroy
      @books = Book.find(params[:id])
    @books.destroy
    redirect_to action: "index"
    end

  def assign_tag
    @tags = Tag.all
    @books = Book.all
  end

  def assign_tag_to
    tag = Tag.find_by_id(params[:tag_id])
    Book.where(id: params[:books_ids]).each do |book|
      BookTag.find_or_create_by(book_id: book.id, tag_id: tag.id)
    end
    redirect_to books_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_books
    @books = Book.find(params[:books_ids])
  end

  def handle_search
    @books = @books.joins(:tags).where("tags.id = ?", params["tag_id"]) if params["tag_id"].present?
    @books = @books.where(price: params["search_price"].to_i) if params["search_price"].present?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/assign_tag.html.erb
<div style="margin-block: 35px;">
  <h2>Assign Tag To Books</h2> 
</div>
<form action="<%= assign_tag_to_books_path %>" method="post">
  <input type="hidden" name="_method" value="put" />
  <%= token_tag %> 

  <select class="custom-select" name="tag_id" id="inputGroupSelect01" style="margin-block: 10px;"> 
    <option selected>Choose Tag</option>
    <% @tags.each do |tag| %>
      <option value= <%= tag.id %> ><%= tag.name %></option>
    <% end %>
  </select>

  <div style="width: 100%;">
    <select class="custom-select" name="books_ids[]" id="selectpicker" style="width: 100%;" multiple >
      <option selected disabled=true>Choose Books</option>
      <% @books.each do |books| %>
        <option value= <%= books.id %> ><%= books.title %></option>
      <% end %>
    </select>
  </div>

  <button type="submit" class="btn btn-primary" style="margin-top: 20px;">Submit</button>
</form>

app/views/books/index.html.erb
<div class="row" style="margin-block: 35px;">
  <div class="col-9">
    <h2>Books Details</h2> 
  </div>
  <div class="col">
    <%= link_to 'Assigning Tags To Books', assign_tag_books_path, class: "btn btn-light", style: "padding-inline: 20px;" %>
  </div>
</div>

<form action="/books" method="GET" class="row">
  <div class="col-3">
    <input type="decimal" name="search_price" class="form-control" placeholder="Search Price" value=<%=params["search_price"]%> >
  </div>
  <div class="col-3">
    <select class="custom-select" name="tag_id" id="inputGroupSelect01"> 
      <option value="0" disabled <%=params["tag_id"].present? ? '' 
        : 'selected' %>>Choose Tag</option>
      <% @tags.each do |tag| %>
        <option value= <%= tag.id %> <%= tag.id == params["tag_id"].to_i ? 'selected' 
        : '' %>><%= tag.name %></option>
      <% end %>
    </select>
  </div>
  <div class="col-3">
    <button type="submit" class="btn btn-primary" >Search</button>
    <%= link_to 'Reset', books_path, class: 'btn btn-light' %>
  </div>
</form>
<br>
  

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
      <th scope="col">Tags</th>
      <th scope="col">Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.price %></td>
        <td>
          <% book.tags.each do |tag| %>
            <div class="btn btn-primary" style="margin-bottom: 5px;"><%= tag.name %></div>
          <% end %>
        </td>
        <td>
          <div style="margin-bottom: 5px;"><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application'%>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.14/css/bootstrap-multiselect.css" type="text/css"/>
  </head>

  <body>
    <div class= "container">
      <%= yield %>
    </div>
    <script src="http://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.14/js/bootstrap-multiselect.js"></script>
    <script type="text/javascript">
      $('#selectpicker').multiselect();
      // var ready = function() {
      // };
      // $(document).ready(ready);
      // $(document).on('turbolinks:load', ready);
    </script>
  </body>
</html>